/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgRouteImport } from './routes/og'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as HoursIndexRouteImport } from './routes/hours.index'
import { Route as HoursIdRouteImport } from './routes/hours.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursIndexRoute = HoursIndexRouteImport.update({
  id: '/hours/',
  path: '/hours/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursIdRoute = HoursIdRouteImport.update({
  id: '/hours/$id',
  path: '/hours/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/rules': typeof RulesRoute
  '/api/health': typeof ApiHealthRoute
  '/hours/$id': typeof HoursIdRoute
  '/hours/': typeof HoursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/rules': typeof RulesRoute
  '/api/health': typeof ApiHealthRoute
  '/hours/$id': typeof HoursIdRoute
  '/hours': typeof HoursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/rules': typeof RulesRoute
  '/api/health': typeof ApiHealthRoute
  '/hours/$id': typeof HoursIdRoute
  '/hours/': typeof HoursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/og' | '/rules' | '/api/health' | '/hours/$id' | '/hours/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/og' | '/rules' | '/api/health' | '/hours/$id' | '/hours'
  id:
    | '__root__'
    | '/'
    | '/og'
    | '/rules'
    | '/api/health'
    | '/hours/$id'
    | '/hours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OgRoute: typeof OgRoute
  RulesRoute: typeof RulesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  HoursIdRoute: typeof HoursIdRoute
  HoursIndexRoute: typeof HoursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours/': {
      id: '/hours/'
      path: '/hours'
      fullPath: '/hours/'
      preLoaderRoute: typeof HoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours/$id': {
      id: '/hours/$id'
      path: '/hours/$id'
      fullPath: '/hours/$id'
      preLoaderRoute: typeof HoursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OgRoute: OgRoute,
  RulesRoute: RulesRoute,
  ApiHealthRoute: ApiHealthRoute,
  HoursIdRoute: HoursIdRoute,
  HoursIndexRoute: HoursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
